services:
  - type: web
    name: unitech-erp
    env: node
    rootDir: backend
    buildCommand: npm install && npm --prefix ../unitech-frontend install && npm --prefix ../unitech-frontend run build
    startCommand: npm install && npm start
    autoDeploy: true
